version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
      REDMINE_DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: example
    volumes:
      - ./redmine_dbpg:/var/lib/postgresql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'